
<?php

require("_db.php");
require_once '../duo_web.php';

//define('USERNAME', $row['username']);
//define('PASSWORD', $row['password']);

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY', "580f3770e7b022dab40c4292b15c5bac4ac85003");

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page. For security reasons, these keys are best stored
 * outside of the webroot in a production implementation.
 */
define('IKEY', "DIZ5YU22LMRYOJWXP8WG");
define('SKEY', "bR8U9GIg3gn1fc7QfBrNwru9aackCVdk4WHapGzp");
define('HOST', "api-3e063fba.duosecurity.com");

$username=$_POST['username'];
$password=$_POST['password'];

$spf=mysql_query("Select username,password from user_login where username='$username' and password='$password' ");
$row=mysql_fetch_array($spf);


if(isset($_GET['login_attempt']))
{
	$spf=sprintf("Select * from user_login where username='%s' and password='%s'",$_POST['username'],md5($_POST['password']));
	$rs=mysql_query($spf);
	$rw=mysql_fetch_array($rs);
	$rc=mysql_num_rows($rs);
	
	if($rc==1)
	{
		$_SESSION['login_hash']=$rw['login_hash'];
		$_SESSION['login_user']=$rw['username'];
		 /*
         * Perform secondary auth, generate sig request, then load up Duo
         * javascript and iframe.
         */
		
		require_once ("verify.php");
	}
	else{echo "<script>window.location='dashboard.php'</script>";}
}

else{
	echo "<form id='loginform' action='index.php?login_attempt=1' method='post'>";
    echo "<p class='animate4 bounceIn'><input type='text' id='username' name='username' required='required' placeholder='Username' /></p>";
    echo "<p class='animate5 bounceIn'><input type='password' id='password' name='password' required='required' placeholder='Password' /></p>";
    echo "<p class='animate6 bounceIn'><button class='btn btn-default btn-block'>Login</button></p>";
	echo "<h4 /><a href='../daftar.html'>&nbsp;Buat Akun Baru&nbsp;</a>  &nbsp; &nbsp; &nbsp; &nbsp; || &nbsp;&nbsp; <a href='../lupa_password.html'>&nbsp; Lupa Password Anda? &nbsp;</a>";
	echo "</form>";
}
echo "";
?>

