
<?php

require("_db.php");
require_once '../duo_web.php';

//define('USERNAME', $row['username']);
//define('PASSWORD', $row['password']);

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY', "580f3770e7b022dab40c4292b15c5bac4ac85003");

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page. For security reasons, these keys are best stored
 * outside of the webroot in a production implementation.
 */
define('IKEY', "DISM8WGH80ORWR69MHIH");
define('SKEY', "TrX4V1qnmiD3pFKNtpDpEdxx2vDjkCZrH7ZnDfPs");
define('HOST', "api-2541faf4.duosecurity.com");

$username=$_POST['username'];
$password=$_POST['password'];

$spf=mysql_query("Select username,password from user_login where username='$username' and password='$password' ");
$row=mysql_fetch_array($spf);

?>

<form id="loginform" action="index.php?login_attempt=1" method="post">
    <p class="animate4 bounceIn"><input type="text" id="username" name="username" required="required" placeholder="Username" /></p>
    <p class="animate5 bounceIn"><input type="password" id="password" name="password" required="required" placeholder="Password" /></p>
    <p class="animate6 bounceIn"><button class="btn btn-default btn-block">Login</button></p>
	<h4 /><a href="../daftar.html">&nbsp;Buat Akun Baru&nbsp;</a>  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;|| &nbsp;&nbsp; <a href="../lupa_password.html">&nbsp; Lupa Password Anda? &nbsp;</a>
 	
</form>
<?php
if(isset($_GET['login_attempt']))
{
	$spf=sprintf("Select * from user_login where username='%s' and password='%s'",$_POST['username'],md5($_POST['password']));
	$rs=mysql_query($spf);
	$rw=mysql_fetch_array($rs);
	$rc=mysql_num_rows($rs);
	
	if($rc==1)
	{
		$_SESSION['login_hash']=$rw['login_hash'];
		$_SESSION['login_user']=$rw['username'];
		$sig_request = Duo::signRequest(IKEY, SKEY, AKEY, $_POST['username']);
	     /*
         * Perform secondary auth, generate sig request, then load up Duo
         * javascript and iframe.
         */
		 

    ?>
		<h3 align="center" /><a href="#">Verifikasi 2 Langkah Untuk Login Voting</a>

        <script type="text/javascript" src="Duo-Web-v2.js"></script>
        <link rel="stylesheet" type="text/css" href="Duo-Frame.css">
        <iframe id="duo_iframe" frameborder="0" data-host="<?php echo HOST; ?>" data-sig-request="<?php echo $sig_request; ?>"></iframe>
	<?php
	}
}

/*
 * STEP 3:
 * Once secondary auth has completed you may log in the user
 */
else if (isset($_POST['sig_response'])) {
    /*
     * Verify sig response and log in user. Make sure that verifyResponse
     * returns the username we logged in with. You can then set any
     * cookies/session data for that username and complete the login process.
     */
    
	$resp = Duo::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
	if ($resp === $row['username']) {
        // Password protected content would go here.
        echo 'Hi, ' . $resp . '<br>';
        echo "<script>window.location='dashboard.php'</script>";
    }
}

else{echo "";}
echo "";
?>